name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: build and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: output variables
        id: variables
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/drone-aws-elastic-beanstalk
          GIT_VERSION=${GITHUB_REF#refs/tags/v}
          DATE_NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          IMAGE_TAGS="${IMAGE_NAME}:${GIT_VERSION},${IMAGE_NAME}:latest"
          LABELS="org.label-schema.build-date=${DATE_NOW},org.label-schema.vcs-ref=$(git rev-parse --short HEAD),org.label-schema.version=${GIT_VERSION}"
          echo ::set-output name=tags::${IMAGE_TAGS}
          echo ::set-output name=labels::${LABELS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.variables.outputs.tags }}
          labels: ${{ steps.variables.outputs.labels }}
